---
releases: https://bbbonnibel.github.io/carrion-userscripts/script/
homepage: https://bbbonnibel.github.io/carrion-userscripts/
icon64: https://bbbonnibel.github.io/carrion-userscripts/icon-64.png
icon: https://bbbonnibel.github.io/carrion-userscripts/icon-32.png
